import type { PossibleErrorsRules } from './types';

const rules: PossibleErrorsRules = {
    'for-direction': ['off'],
    'getter-return': ['off'],
    'no-async-promise-executor': ['off'],
    'no-await-in-loop': ['off'],
    'no-compare-neg-zero': ['off'],
    'no-cond-assign': ['off'],
    'no-console': ['off'],
    'no-constant-condition': ['off'],
    'no-control-regex': ['off'],
    'no-debugger': ['off'],
    'no-dupe-args': ['off'],
    'no-dupe-else-if': ['off'],
    'no-dupe-keys': ['off'],
    'no-duplicate-case': ['off'],
    'no-empty': ['off'],
    'no-empty-character-class': ['off'],
    'no-ex-assign': ['off'],
    'no-extra-boolean-cast': ['off'],
    'no-func-assign': ['off'],
    'no-import-assign': ['off'],
    'no-inner-declarations': ['off'],
    'no-invalid-regexp': ['off'],
    'no-irregular-whitespace': ['off'],
    'no-misleading-character-class': ['off'],
    'no-obj-calls': ['off'],
    'no-promise-executor-return': ['off'],
    'no-prototype-builtins': ['off'],
    'no-regex-spaces': ['off'],
    'no-setter-return': ['off'],
    'no-sparse-arrays': ['off'],
    'no-template-curly-in-string': ['off'],
    'no-unexpected-multiline': ['off'],
    'no-unreachable': ['off'],
    'no-unreachable-loop': ['off'],
    'no-unsafe-finally': ['off'],
    'no-unsafe-negation': ['off'],
    'no-unsafe-optional-chaining': ['off'],
    'no-useless-backreference': ['off'],
    'require-atomic-updates': ['off'],
    'use-isnan': ['off'],
    'valid-typeof': ['off']
};

export default rules;
